server:
  port: 8761
eureka:
  instance:
    hostname: eureka-server
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  security:
    user:
      name: admin
      password: admin123

logging:
  config: classpath:logback.xml
  level:
    root: info