server:
  port: 8751
spring:
  application:
    name: goods-server
# 指定数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/campus?useUnicode=true&amp;characterEncoding=UTF8
    username: root
    password: 666666
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 5
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  thymeleaf:
    prefix: classpath:/static/  #prefix：指定模板所在的目录
    check-template-location: true  #check-tempate-location: 检查模板路径是否存在
    cache: false  #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
    suffix:  .html
    encoding: UTF-8
    mode: LEGACYHTML5

  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /static/

  #redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
    password:
    jedis:
      pool:
        max-active: 8
        min-idle: 1
        max-idle: 1
        max-wait: 100
    timeout: 6000

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

eureka:
  instance:
    hostname: eureka-server
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://admin:admin123@${eureka.instance.hostname}:8761/eureka

# 配置日志级别
logging:
  config: classpath:logback.xml
  level:
    root: info

#轮询超时时间
ribbon:
  ReadTimeout: 600000
  ConnectTimeout: 600000