# bootstrap.yml配置文件相对于application更优先
spring:
  application:
    name: zuul-server

server:
  port: 8762
eureka:
  instance:
    hostname: eureka-server
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://admin:admin123@${eureka.instance.hostname}:8761/eureka

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  #不忽略任何头部信息，所有header都转发到下游的资源服务器
  sensitiveHeaders:
  #不忽略框架与权限相关的头信息
  ignoreSecurityHeaders: false
  routes:
    cas-server:
      path: /**
      serviceId: cas-server
      sensitiveHeaders:
  semaphore:
    max-semaphores: 5000
  ribbonIsolationStrategy: THREAD

hystrix:
  threadpool:
    default:
      coreSize: 100
      maximumSize: 5000
      allowMaximumSizeToDivergeFromCoreSize: true
      maxQueueSize: -1

  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000000

ribbon:
  ReadTimeout: 600000
  ConnectTimeout: 600000

# 配置日志级别
logging:
  config: classpath:logback.xml
  level:
    root: info

login-url: "http://127.0.0.1:8762/cas-server/login"
